/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { IArticle } from './iArticle';

export interface GetArticlesResponse {
  articles: IArticle[];
}
