/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { IArticleCreatedAt } from './iArticleCreatedAt';
import type { IArticleUpdatedAt } from './iArticleUpdatedAt';
import type { Tag } from './tag';

export interface IArticle {
  author: string;
  title: string;
  content: string;
  tags: Tag[];
  createdAt: IArticleCreatedAt;
  updatedAt: IArticleUpdatedAt;
}
