/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export * from './getArticlesParams';
export * from './getArticlesQueryParams';
export * from './getArticlesResponse';
export * from './iArticle';
export * from './iArticleCreatedAt';
export * from './iArticleUpdatedAt';
export * from './tag';
