/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type Tag = (typeof Tag)[keyof typeof Tag];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Tag = {
  JavaScript: 'JavaScript',
  Machine_Learning: 'Machine Learning',
  Nutrition: 'Nutrition',
  Exercise: 'Exercise',
  Adventure: 'Adventure',
  Movies: 'Movies',
  Personal_Finance: 'Personal Finance',
  Fashion: 'Fashion',
} as const;
